CREATE TABLE IF NOT EXISTS songs (
    id CHAR(8) NOT NULL COMMENT 'ID',
    name VARCHAR(50) NOT NULL COMMENT '楽曲名',
    level TINYINT(2) UNSIGNED NOT NULL COMMENT '楽曲Lv',
    publish_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '公開日時',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='楽曲';

INSERT INTO songs (
    id,
    name,
    level
) VALUES (
    'zzzzzzzz',
    'テスト楽曲',
    1
);
